# Generated by Django 5.2.5 on 2025-08-19 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_patient_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='patient',
        ),
        migrations.AlterModelOptions(
            name='workplace',
            options={'verbose_name_plural': 'Workplaces'},
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
        migrations.DeleteModel(
            name='TestResult',
        ),
    ]
