# Generated by Django 5.2.5 on 2025-08-19 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_remove_testresult_patient_alter_workplace_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='address',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='workplaces',
        ),
        migrations.AddField(
            model_name='appointment',
            name='workplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='auth_app.workplace'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='workplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='auth_app.workplace'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='license_number',
            field=models.CharField(default='0', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(default='Généraliste', max_length=100),
        ),
    ]
