# Generated by Django 5.2.5 on 2025-08-19 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_remove_doctor_address_remove_doctor_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='workplace',
        ),
        migrations.AddField(
            model_name='doctor',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='workplaces',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='auth_app.workplace'),
        ),
        migrations.AddField(
            model_name='patient',
            name='assigned_doctors',
            field=models.ManyToManyField(blank=True, related_name='assigned_patients', to='auth_app.doctor'),
        ),
        migrations.AddField(
            model_name='referral',
            name='referred_by',
            field=models.ForeignKey(blank=True, help_text='Médecin qui a effectué le référencement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_by_me', to='auth_app.doctor'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='license_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referred_to',
            field=models.ForeignKey(help_text='Médecin référé', on_delete=django.db.models.deletion.CASCADE, related_name='referred_patients', to='auth_app.doctor'),
        ),
    ]
