# Generated by Django 5.2.5 on 2025-08-19 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0008_remove_doctor_workplace_doctor_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField()),
                ('reason_for_appointment', models.TextField()),
                ('deletion_reason', models.CharField(max_length=50)),
                ('deletion_comment', models.TextField(blank=True, null=True)),
                ('deletion_date', models.DateTimeField(auto_now_add=True)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_appointments', to='auth_app.doctor')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_appointments', to='auth_app.patient')),
                ('workplace', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_appointments', to='auth_app.workplace')),
            ],
        ),
    ]
