# Generated by Django 5.2.5 on 2025-08-20 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0010_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='auth_app.patient'),
        ),
    ]
