# Generated by Django 5.2.5 on 2025-08-20 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0012_note_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplace',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workplaces', to='auth_app.doctor'),
        ),
    ]
