# Generated by Django 5.2.5 on 2025-10-04 11:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0015_remove_doctor_first_name_remove_doctor_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_used', models.BooleanField(default=False, verbose_name='Utilisé')),
                ('email_associated', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email associé (optionnel)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('used_by_doctor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_app.doctor', verbose_name='Docteur ayant utilisé le code')),
            ],
            options={
                'verbose_name': "Code d'Enregistrement",
                'verbose_name_plural': "Codes d'Enregistrement",
                'ordering': ['-created_at'],
            },
        ),
    ]
